### PR TITLE
Initial addition of dgs-framework compatability impl

### PR DESCRIPTION
**Pull request by setchy**
#18 - there may be a few bumps to still work through...

When running `npm run test dgs` (or any other impl) locally it would hang at `Starting containers...`. 🤷‍♂️ 

I did check the dgs image in isolation and everything lgtm 🤞

### CODE REVIEW

**Comment by setchy** [comment]
I've noted that the `dgs-framework` doesn't allow exposing the GraphQL API endpoint at the base/root.  Raised https://github.com/Netflix/dgs-framework/discussions/615 to discuss with their maintainers.

In the interim, locally I've made the following changes and can confirm it works

- supergraph.yaml -> `subgraphs:products:routing_url` to http://products:4001/graphql and
- client.ts -> line 8, const productsUrl = "http://localhost:4001/graphql"

Depending on how the dgs discussion plays out, it may be resolved it may be possible in a later release, or, the compatibility harness might need to allow implementations to specific the products subgraph url

**Comment by paulbakker** [comment]
There's not really any reason why we couldn't run on `/`, so we can fix that in the validation.

**Comment by setchy** [comment]
Awesome, thanks @paulbakker 👏

**Comment by paulbakker** [comment]
PR: https://github.com/Netflix/dgs-framework/pull/622

**Comment by michael-watson** [comment]
Thanks a ton @paulbakker for the quick fix and big thanks to @setchy for the contribution 🎉

**Pull request merged**
