### PR TITLE
Update README with new report format and TOC

### PR DESCRIPTION
**Pull request by dariuszkuc**

### CODE REVIEW

**Comment by dariuszkuc** [comment]
Sadly Github formatting of markdown tables is pretty much non-existent.... 

If we do want to improve the formatting then we can

* rewrite report generation logic to generate HTML `<table>` instead of markdown
  * we would need to verify https://www.apollographql.com/docs/federation/other-servers still renders correctly (Gatsby generates all tables using max width)
* wrap first header in a `<div>` with some width matching longest lib name
  * it is a hacky solution but does work 🤷

**Comment by hwillson** [comment]
Thanks for this @dariuszkuc! I agree with exploring either of those options. 👍

**Comment by dariuszkuc** [comment]
> wrap first column header in a <div> with some width matching longest lib name

While both VSCode and IntelliJ render the markdown correctly on my local, it looks like Github does not like it :( So guess generating HTML `<table>` might be the only option.

**Comment by dariuszkuc** [comment]
Additional context -> above solution using `<div>` used to work in the past but doesn't work anymore as Github sanitizes CSS in markdown. So in order to force the width, we have to use HTML that has a width property, e.g. empty image `` or specify width in the table columns

**Pull request merged**
