### PR TITLE
update apollo-federation-php with latest schema changes

### PR DESCRIPTION
**Pull request by dariuszkuc**
See https://github.com/apollographql/apollo-federation-subgraph-compatibility/issues/166 for details.

Resolves https://github.com/apollographql/apollo-federation-subgraph-compatibility/issues/193

### CODE REVIEW

**Comment by dariuszkuc** [comment]
## Federation PHP Compatibility Results
<table>
<thead>
<tr><th>Federation 1 Support</th><th>Federation 2 Support</th></tr>
</thead>
<tbody>
<tr><td><table><tr><th><code>_service</code></th><td>❌</td></tr><tr><th><code>@key (single)</code></th><td>❌</td></tr><tr><th><code>@key (multi)</code></th><td>🔲</td></tr><tr><th><code>@key (composite)</code></th><td>🔲</td></tr><tr><th><code>repeatable @key</code></th><td>🟢</td></tr><tr><th><code>@requires</code></th><td>🔲</td></tr><tr><th><code>@provides</code></th><td>🟢</td></tr><tr><th><code>federated tracing</code></th><td>🔲</td></tr></table></td><td><table><tr><th><code>@link</code></th><td>❌</td></tr><tr><th><code>@shareable</code></th><td>🔲</td></tr><tr><th><code>@tag</code></th><td>🔲</td></tr><tr><th><code>@override</code></th><td>🔲</td></tr><tr><th><code>@inaccessible</code></th><td>🔲</td></tr></table></td></tr>
</tbody>
</table>

**Comment by rvanlaak** [comment]
Does the above comment on this PR mean that the support as documented on the [Apollo support pages](https://www.apollographql.com/docs/federation/building-supergraphs/supported-subgraphs/#php) is different as expected?

**Comment by rvanlaak** [comment]
Would it be an idea to create a follow-up ticket to test the most popular and promising PHP libraries as documented on https://graphql.org/code/#php ?

**Comment by dariuszkuc** [comment]
>Does the above comment on this PR mean that the support as documented on the [Apollo support pages](https://www.apollographql.com/docs/federation/building-supergraphs/supported-subgraphs/#php) is different as expected?

There was a bug (fixed) in how the tests were run (testing old code vs actually changed code) - [latest results from CI/CD](https://apollographql.github.io/apollo-federation-subgraph-compatibility/#php) show the correct results that are the same as published on our [docs page](https://www.apollographql.com/docs/federation/building-supergraphs/supported-subgraphs/#php).

>Or, given that [the composer.json](https://github.com/apollographql/apollo-federation-subgraph-compatibility/blob/main/implementations/php/composer.json) in this repo's implementations/php folder requires both the webonyx/graphql-php and skillshare/apollo-federation-php, does that mean that solely the skillshare package is actively tested? Because if so, then it might be better to rename that PHP folder to include that library?

Many GraphQL libraries follow the pattern of "core" library, federation library and high level framework (sometimes they are combined). As documented on our test results page `webonyx/graphql-php` (reference implementation of GraphQL in PHP) implementation is tested together with `skillshare/apollo-federation-php` which is a federation library. As per the [GraphQL PHP maintainers](https://github.com/webonyx/graphql-php/issues/515) there are not planning on adding built-in federation support in the core library and they suggest adding the support through additional libraries (i.e `skillshare/apollo-federation-php`).

>Would it be an idea to create a follow-up ticket to test the most popular and promising PHP libraries as documented on https://graphql.org/code/#php ?

You can open a ticket but since integrations are primarily community driven, a PR with example integration would be even better. Check out the [subgraph maintainers implementation guide](https://github.com/apollographql/apollo-federation-subgraph-compatibility/blob/main/SUBGRAPH_GUIDE.md), [information about executed tests](https://github.com/apollographql/apollo-federation-subgraph-compatibility/blob/main/COMPATIBILITY.md) and [contributing guide](https://github.com/apollographql/apollo-federation-subgraph-compatibility/blob/main/CONTRIBUTING.md) for more details.

**Pull request merged**
