### PR TITLE
add inventory type to sangria implementation to pass test for @interfaceObject support

### PR DESCRIPTION
**Pull request by oskargotte**
Bump sangria-federation to latest version which supports the @interfaceObject directive.
Add the Inventory entity object type with Key and InterfaceObject directives to the schema in order to pass the compatibility test for @interfaceObject.

### CODE REVIEW

**Comment by dariuszkuc** [comment]
@oskargotte is this still a draft?

**Review by dariuszkuc — APPROVED** [review]

**Comment by dariuszkuc** [comment]
Looks like `@composeDirective` (https://github.com/sangria-graphql/sangria-federated/issues/221) is also supported. Do you mind updating the test to also cover that scenario?

**Comment by oskargotte** [comment]
> @oskargotte is this still a draft?

Well it’s pretty much finilized but I wanted to give @yanns a chance to provide feedback before merging it.

**Comment by oskargotte** [comment]
> Looks like `@composeDirective` ([sangria-graphql/sangria-federated#221](https://github.com/sangria-graphql/sangria-federated/issues/221)) is also supported. Do you mind updating the test to also cover that scenario?

Yes the composeDirective is supported in sangria-federated but I'll have to read up on the requirements to get the tests to pass. But I acn target that one in another PR.

**Review by yanns — APPROVED** [review]
💯

**Comment by oskargotte** [comment]
> > @oskargotte is this still a draft?
> 
> Well it’s pretty much finilized but I wanted to give @yanns a chance to provide feedback before merging it.

Should be ready to merge now @dariuszkuc

**Review by yanns — APPROVED** [review]

**Pull request merged**
