### PR TITLE
upgrade to cdk v2

### PR DESCRIPTION
**Pull request by asenousy**
Just need to upgrade the appsync implementation to use CDK v2

### CODE REVIEW

**Comment by dariuszkuc** [comment]
Thanks for the PR. It looks like [composition fails](https://github.com/apollographql/apollo-federation-subgraph-compatibility/actions/runs/6433218163/job/17469827203) with following:

* INVALID_GRAPHQL: [products] Directive "@extends" may not be used on SCHEMA.
* INVALID_GRAPHQL: [products] Name "__typename" must not begin with "__", which is reserved by GraphQL introspection.

First one should be an easy fix -> https://github.com/apollographql/apollo-federation-subgraph-compatibility/blob/main/implementations/appsync/cdk/products-service/src/products-service.graphql#L2

Unsure about the second one as that should be a scalar and not an input type (https://github.com/apollographql/apollo-federation-subgraph-compatibility/blob/main/implementations/appsync/cdk/products-service/src/products-service.graphql#L82C7-L82C11)

**Comment by dariuszkuc** [comment]
Thanks for the fixes. Looks I got a bug in the workflow as it checks out code from `main` instead of your branch (hence the failure in composition https://github.com/apollographql/apollo-federation-subgraph-compatibility/actions/runs/6457988795/job/17530722881).

I tried running it locally and it looks like target AppSync instance is still not accessible (https://github.com/apollographql/apollo-federation-subgraph-compatibility/issues/440). By any chance could you help out with that as well?

**Review by dariuszkuc — APPROVED** [review]

**Comment by dariuszkuc** [comment]
Can you send me DM on our [community forums](https://community.apollographql.com/g/Ecosystem) OR [discord server](https://discord.gg/graphos)?

**Comment by asenousy** [comment]
i signed up to community forums, but it doesn't allow me to DM you as i am a new user for some reason, can you send me a message that i can reply back to. my username is asenousy

**Comment by dariuszkuc** [comment]
Msg sent 🚀

**Pull request merged**
