### PR TITLE
Test gqlgen update for compatibility

### PR DESCRIPTION
**Pull request by StevenACoffman**
Hello, This is a WIP to see if the recent https://github.com/99designs/gqlgen/pull/2371 would fix the subgraph compatibility problem reported by https://github.com/99designs/gqlgen/issues/2357

Not sure how to run the full suite, but this is an attempt to trigger it.

### CODE REVIEW

**Comment by StevenACoffman** [comment]
@lleadbet @dariuszkuc I am looking for help on how to see the test failures here that caused the recent regression in  #223 regarding Federation V1 compatibility for gqlgen.

**Comment by dariuszkuc** [comment]
Hello 👋 

For repro:
1. uncomment `@requires` directive from [schema.graphqls](https://github.com/apollographql/apollo-federation-subgraph-compatibility/blob/main/implementations/gqlgen/graph/schema.graphqls#L68)
2. start gateway + subgraphs locally (see  [CONTRIBUTING.md](https://github.com/apollographql/apollo-federation-subgraph-compatibility/blob/main/CONTRIBUTORS.md#debugging-at-the-command-line) for details)
3. run following query against the gateway to observe the broken behavior

```
query {
  product(id: "apollo-federation") {
    createdBy {
      averageProductsCreatedPerYear
      email
    }
  }
}
```

OR run following against gqlgen server directly

```graphql
query {
    _entities(representations: [{ "__typename": "User", "email": "support@apollographql.com" }]) {
        ...on User {
          averageProductsCreatedPerYear
          email
        }
      }
    }
}
```
```

**Comment by dariuszkuc** [comment]
You can see the compatibility test results under checks -> https://github.com/apollographql/apollo-federation-subgraph-compatibility/actions/runs/3063889683 (NOTE: `@requires` is currently commented out from the schema)

**Comment by dariuszkuc** [comment]
Closing this PR as it does not fix the underlying issue.

**Pull request closed without merging**
