### PR TITLE
Upgrade elixir deps

### PR DESCRIPTION
**Pull request by kdawgwilk**
This bumps some elixir dependencies and also fixes the docker build

### CODE REVIEW

**Comment by kdawgwilk** [comment]
Looks like its actually the second assertion that is failing so this one instead
```javascript
const basicallyTheSame = compareSchemas(productsPing.data?._service?.sdl);
```
Test failure from github action log
```
introspection
    expect(received).toBe(expected) // Object.is equality
    Expected: true
    Received: false
      15 |   const basicallyTheSame = compareSchemas(productsPing.data?._service?.sdl);
      16 |
    > 17 |   expect(basicallyTheSame).toBe(true);
         |                            ^
      18 | });
      19 |
      at Object.<anonymous> (src/tests/introspection.test.ts:17:28)
```
Any ideas on how to narrow down how they are different?

**Comment by dariuszkuc** [comment]
Indeed. Sadly the [unit test](https://github.com/apollographql/apollo-federation-subgraph-compatibility/blob/main/src/utils/schemaComparison.ts#L41) is pretty crude... It checks whether the expected objects are there but doesn't tell us what is missing.

Can you check what is the output of the `_service { sdl }` query and compare that against the [expected schema](https://github.com/apollographql/apollo-federation-subgraph-compatibility#products-schema-to-be-implemented-by-library-maintainers)?

**Comment by kdawgwilk** [comment]
Looks like its because the absinthe library doesn't currently strip off `_resolveReference` fields when it renders the SDL.  This has been a complicated topic for us to address in the elixir library because of how absinthe eagerly strips off types that are not referenced/accessible in the schema.

**Comment by kdawgwilk** [comment]
This is the rendered SDL
```graphql
"Represents a schema"
schema {
  query: Query
}

"""
type ProductVariation {
  id: ID!
}
"""
type ProductVariation {
  id: ID!
}

type _Service {
  sdl: String
}

"a union of all types that use the @key directive"
union _Entity = User | Product

"""
extend type Query {
  product(id: ID!): Product
}
"""
type Query @extends {
  """
  The _service field on the query root returns SDL
  which includes all of the service's types (after any non-federation transforms),
  as well as federation directive annotations on the fields and types.
  The federation schema modifications (i.e. new types and directive definitions)
  should not be included in this SDL.
  """
  _service: _Service!

  """
  Returns a non-nullable list of _Entity types
  and have a single argument with an argument name of representations
  and type [_Any!]! (non-nullable list of non-nullable _Any scalars).
  The _entities field on the query root must allow a list of _Any scalars
  which are "representations" of entities from external services.
  These representations should be validated with the following rules:

  - Any representation without a __typename: String field is invalid.
  - Representations must contain at least the fields defined in the fieldset of a @key directive on the base type.
  """
  _entities(representations: [_Any!]!): [_Entity]!

  product(id: ID!): Product
}

"The _Any scalar is used to pass representations of entities from external services into the root _entities field for execution."
scalar _Any

"""
type Product @key(fields: "id") @key(fields: "sku package") @key(fields: "sku variation { id }") {
  id: ID!
  sku: String
  package: String
  variation: ProductVariation
  dimensions: ProductDimension
  createdBy: User @provides(fields: "totalProductsCreated")
}
"""
type Product @key(fields: "sku variation { id }") @key(fields: "sku package") @key(fields: "id") {
  id: ID!
  sku: String
  package: String
  variation: ProductVariation
  dimensions: ProductDimension
  createdBy: User @provides(fields: "totalProductsCreated")
  _resolveReference: Product
}

"""
type ProductDimension {
  size: String
  weight: Float
}
"""
type ProductDimension {
  size: String
  weight: Float
}

"""
extend type User @key(fields: "email") {
  email: ID! @external
  totalProductsCreated: Int @external
}
"""
type User @extends @key(fields: "email") {
  email: ID! @external
  totalProductsCreated: Int @external
  _resolveReference: User
}
```

**Comment by kdawgwilk** [comment]
Fix for rendering these fields is here https://github.com/DivvyPayHQ/absinthe_federation/pull/55

**Comment by kdawgwilk** [comment]
Alright this now includes that fix and here are the test results now

<table>
<thead>
<tr><th width="300">Library</th><th>Federation 1 Support</th><th>Federation 2 Support</th></tr>
</thead>
<tbody>
<tr><td><a href="https://github.com/DivvyPayHQ/absinthe_federation">Absinthe.Federation</a></td><td><table><tr><th>_service</th><td>✅</td></tr><tr><th>`@key` (single)</th><td>✅</td></tr><tr><th>`@key` (multi)</th><td>✅</td></tr><tr><th>`@key` (composite)</th><td>✅</td></tr><tr><th>`@requires`</th><td>✅</td></tr><tr><th>`@provides`</th><td>✅</td></tr><tr><th>`@ftv1`</th><td>❌</td></tr></table></td><td><table><tr><th>`@link`</th><td>❌</td></tr><tr><th>`@shareable`</th><td>❌</td></tr><tr><th>`@tag`</th><td>❌</td></tr><tr><th>`@override`</th><td>❌</td></tr><tr><th>`@inaccessible`</th><td>❌</td></tr></table></td></tr>
</tbody>
</table>

**Review by dariuszkuc — APPROVED** [review]
Awesome! Thanks!

**Pull request merged**
