### PR TITLE
update gqlgen to v0.17.45

### PR DESCRIPTION
**Pull request by StevenACoffman**
This updates gqlgen to v0.17.45

### CODE REVIEW

**Comment by StevenACoffman** [comment]
@dariuszkuc I'm not sure if I need to do anything else to regenerate the test results summary page.

**Review by dariuszkuc — CHANGES_REQUESTED** [review]
I believe you might want to uncomment https://github.com/apollographql/apollo-federation-subgraph-compatibility/blob/ff24a67687fe96b76edab303f0e2854ea2b9b863/implementations/gqlgen/graph/schema.graphqls#L68

**Comment by StevenACoffman** [comment]
@jesse-apollo You will probably need to pick this up and carry this PR the rest of the way home, as I'm traveling and it's hard to code on my phone while driving. 😆

**Comment by jesse-apollo** [comment]
Hi @StevenACoffman I'll take a look at this today.

**Comment by jesse-apollo** [comment]
@StevenACoffman I've got everything passing locally.  Do you want to close this PR and I'll create a new one or add me to your test repo? Or I can PR against your test repo.

**Comment by jesse-apollo** [comment]
Here are my changes: https://github.com/jesse-apollo/apollo-federation-subgraph-compatibility/commit/26e9536943f239ecee035291358d914408fbc03d

**Comment by StevenACoffman** [comment]
I added your commit to this PR, but I'm fine either way!

**Review by dariuszkuc — APPROVED** [review]

**Comment by StevenACoffman** [comment]
@dariuszkuc How does the website get updated with this new info?

**Comment by dariuszkuc** [comment]
👋 its a manual step - I'll update it today or tomorrow.

**Pull request merged**
