### PR TITLE
feat(php): Add Apollo Federation PHP implementation

### PR DESCRIPTION
**Pull request by ldiego08**
This adds the PHP compatibility implementation which leverages [webonyx/graphql-php](https://github.com/webonyx/graphql-php) and [Skillshare/apollo-federation-php](https://github.com/Skillshare/apollo-federation-php) to satisfy the Apollo Federation specification. 

This is based on the `apollo-server` implementation.

cc @lennyburdette

### CODE REVIEW

**Comment by ldiego08** [comment]
@michael-watson ah, interesting. I didn't know you could debug the tests like that. I see the errors in the GitHub action as well. When I run `npm run test php` I only see this:

```
Starting containers...
Library php started successfully
Library php complete!
Stopping containers...
complete
```

Is there a way to see the same output of the tests from the GH action in the local console?

**Comment by lennyburdette** [comment]
https://github.com/apollographql/apollo-federation-subgraph-compatibility/blob/main/CONTRIBUTORS.md#debugging-at-the-command-line


DEBUG=test npm run test

(I found the output to be too noisy to enable by default)

**Comment by ldiego08** [comment]
@michael-watson @lennyburdette I was able to see error locally! Failures were caused by a check we have in the PHP library that checks all keys in the representations arg maps to fields in the entity type which fails for queries like `{ __typename: "Product", sku: "federation", variation: { id: "OSS" } }`. 

I got most tests working, except for `ftv1`. I see it's related to tracing - is there any reference implementation I can follow? I'm also noticing there are some frameworks in the matrix that are not compatible with `ftv1`. Would this acceptable for a first iteration of our library?

**Comment by ldiego08** [comment]
Awesome, @michael-watson! Thank you and @lennyburdette for helping out with this and all the patience! :)

**Pull request merged**
