### PR TITLE
Add Swift Graphiti implementation example

### PR DESCRIPTION
**Pull request by samisuteria**

### CODE REVIEW

**Comment by dariuszkuc** [comment]
Awesome! Could you also add a workflow file for GH action? (see [points 7 and 8](https://github.com/apollographql/apollo-federation-subgraph-compatibility/blob/main/SUBGRAPH_GUIDE.md#how-can-i-have-my-library-included-in-this) in subgraph guide)

**Review by dariuszkuc — APPROVED** [review]

**Comment by dariuszkuc** [comment]
Awesome!

**Comment by samisuteria** [comment]
@dariuszkuc do you know how to update the list of supported libraries here: https://www.apollographql.com/docs/federation/building-supergraphs/supported-subgraphs

**Comment by dariuszkuc** [comment]
Hello 👋 
It is currently a manual process - we need to open up a PR against `apollographql/federation` repo. I opened up a PR with latest changes -> https://github.com/apollographql/federation/pull/2401

**Comment by samisuteria** [comment]
Thanks!

**Pull request merged**
