### PR TITLE
update @requires test to verify the functionality

### PR DESCRIPTION
**Pull request by dariuszkuc**
Updating `users` and `products` subgraph schemas to allow for testing the support of `@requires` functionality in the implementing subgraph. This is a breaking change as we modify the schema so all the existing implementations will be impacted.

**Changes**:
* `users` subgraph
```graphql
type User @key(fields:"email") {
  email:ID!
  name: String
  totalProductsCreated: Int
  yearsOfEmployment: Int! # <-- new field
}
```
* `products` subgraph
```graphql
extend type User @key(fields: "email") {
  averageProductsCreatedPerYear: Int @requires(fields: "yearsOfEmployment") # <-- test `@requires` functionality
  email: ID! @external
  name: String @override(from: "users")
  totalProductsCreated: Int @external
  yearsOfEmployment: Int! @external # <-- field from the users subgraph used by @requires
}
```

Implementation updates will follow in separate PRs.

**Related Issues**:

* https://github.com/apollographql/apollo-federation-subgraph-compatibility/issues/128

### CODE REVIEW

**Comment by kdawgwilk** [comment]
Whats the approach to adding these changes to implementations?  will that be done in this PR?  How can library maintainers help?

**Comment by dariuszkuc** [comment]
@kdawgwilk 👋 I'll split the PR into the schema + test update and will have separate implementations PR. Once the test PR is merged, you will be able to update the implementations without waiting for additional changes from my side. Thanks for the help!

**Comment by ddebrunner** [comment]
Does `CONTRIBUTORS.md` need to be updated?

**Comment by dariuszkuc** [comment]
@ddebrunner yes, I'll update it once the https://github.com/apollographql/apollo-federation-subgraph-compatibility/pull/152 is merged

**Review by hwillson — APPROVED** [review]
Thanks for adding this @dariuszkuc!

**Pull request merged**
