### PR TITLE
Added Hot Chocolate GraphQL Server

### PR DESCRIPTION
**Pull request by michaelstaib**
I have added the Hot Chocolate GraphQL Server as a compliant subgraph.

Hot Chocolate is a GraphQL server for .NET

https://github.com/ChilliCream/hotchocolate

### CODE REVIEW

**Comment by hwillson** [comment]
This is wonderful @michaelstaib - thanks very much! We'll work on getting this merged later today.

**Comment by michaelstaib** [comment]
@hwillson I have updated the package to the release version.

**Review by hwillson — APPROVED** [review]
This is wonderful @michaelstaib - thanks very much for this!

**Comment by michaelstaib** [comment]
Thank you @hwillson for getting this in!

**Comment by lexdevel** [comment]
Great job 👏

**Pull request merged**
